binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO33
      mode:
        input: true
        pullup: true
    name: "WaterCop Open Light"
    on_state:
      then:
        - logger.log: "WaterCop Light A state changed!"
  - platform: gpio
    pin: 
      number: GPIO25
      mode:
        input: true
        pullup: true
    name: "WaterCop Closed Light"
    on_state:
      then:
        - logger.log: "WaterCop Light B state changed!"

switch:
  - platform: gpio
    pin: 
      number: GPIO26
      mode: 
        output: true
    name: "WaterCop Open Switch"
    id: open_switch
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: open_switch

  - platform: gpio
    pin: 
      number: GPIO27
      mode: 
        output: true
    name: "WaterCop Close Switch"
    id: close_switch
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: close_switch