binary_sensor:
  - platform: gpio
    pin: 
      number: D27
      mode:
        input: true
        pullup: true
    name: "WaterCop Light A"
  - platform: gpio
    pin: 
      number: D26
      mode:
        input: true
        pullup: true
    name: "WaterCop Light B"

switch:
  - platform: gpio
    pin: 
      number: D25
      mode: 
        output: true
    name: "WaterCop Open Switch"
    id: open_switch
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: open_switch

  - platform: gpio
    pin: 
      number: D33
      mode: 
        output: true
    name: "WaterCop Close Switch"
    id: close_switch
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: close_switch