switch:
  - platform: gpio
    pin: 
      number: GPIO26
      mode: 
        output: true
    id: open_switch
    name: "WaterCop Open Switch"
    internal: false
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: open_switch

  - platform: gpio
    pin: 
      number: GPIO27
      mode: 
        output: true
    id: close_switch
    name: "WaterCop Close Switch"
    internal: false
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: close_switch

button:
  - platform: template
    name: "Toggle Output"
    id: toggle_button
    on_press:
      if:
        condition:
          lambda: 'return id(watercop_state).state;'
        then:
          - switch.turn_on: close_switch
        else:
          - switch.turn_on: open_switch

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO25
      mode:
        input: true
        pulldown: true
    internal: false
    id: open_light
    name: "WaterCop Open Light"
  
  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pulldown: true
    internal: false
    id: close_light
    name: "WaterCop Close Light"
  
  - platform: template
    id: watercop_state
    name: "WaterCop State"
    lambda: |-
      if (id(open_light).state) {
        return true;
      } else if (id(close_light).state) {
        return false;
      } else {
        return {};
      }

  
